services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatMiniProgramPayBundle\AdminMenu: ~

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  WechatMiniProgramPayBundle\Command\:
    resource: '../../Command/'
  WechatMiniProgramPayBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramPayBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatMiniProgramPayBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatMiniProgramPayBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramPayBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramPayBundle\Service\:
    resource: '../../Service/'
